--- #YAML:1.0
name: Test-utf8
version: 0.02
author: ~
abstract: handy utf8 tests
license: perl
requires:
  Test::Builder: 0.15
build_requires:
  Test::Builder::Tester: 1.01
provides:
  Test::utf8:
    file: lib/Test/utf8.pm
    version: 0.02
generated_by: Module::Build version 0.25
